### ISSUE TITLE
Memory editor: clicks to edit not recognized?

### ISSUE THREAD

**Issue by floooh** [ocornut/imgui_club#16]
I just noticed a weird (new?) behaviour which I didn't notice when I started using the imgui_memory_editor:

When I'm clicking a number to start editing, and the click takes a bit longer, the focus isn't taken, so editing doesn't start. Only when "short-tapping" through a touchpad it seems to work.

I had to replace the IsMouseClicked(0) here:

https://github.com/ocornut/imgui_club/blob/e680ad8d6b9278367d0f71a698beb96b70762ed4/imgui_memory_editor/imgui_memory_editor.h#L394

...with ```IsMouseReleased(0)```. This always seems to work, both with "short taps" and "long clicks", but I don't understand *why*.

Is anybody else seeing this too? Could this be caused by a change of behaviour in newer ImGui versions?

**Comment by ocornut** [comment]
Hello @floooh,

I am not sure I can repro but maybe I don't understand it well (just tried with `master`).

As you clicking on the left side (hex) or right side (ascii display) ?
What do you mean by "focus isn't taken" ? Cursor doesn't appear in the InputText, host window isn't focused and moved to the front ?

Do you get it e.g. in the example app or in any empty-ish app with your backend?

**Comment by floooh** [comment]
Ah sorry I should have provided a more precise description. I recorded a quick GIF in my home computer emulators. The circle shows how long I'm clicking:

![Nov-05-2019 17-22-37](https://user-images.githubusercontent.com/1699414/68225572-ecb48c00-fff0-11e9-9260-e2e97d6c01e5.gif)

I'm not sure whether the reason is how I'm providing mouse input to Dear ImGui (I have a 1 frame debuffering so that a button-down and -up for one mouse button can't happen in the same frame), but for such long clicks this should not matter.

If you cannot reproduce this then please don't waste time with it, I'm mostly interested in the "are you seeing this too?" ;)

**Comment by ocornut** [comment]
Yeah I cannot repro :( Maybe use some tracing/debugging, confirm it is happening with your bindings in an empty app etc.

**Comment by floooh** [comment]
Oki! At least good to know that the error must be somewhere on my side. Thanks for taking the time :)

**Comment by ocornut** [comment]
Please let me know when you understand the issue. I am taking notes toward providing better tools to either debug binding either track subtle errors like that.
