### ISSUE TITLE
Crashing when I scroll to end

### ISSUE THREAD

**Issue by osa3301** [ocornut/imgui_club#21]
anyone know why ? Im running it on win32 vs2019 win10
when I scroll down mem editor it crash for some reason

**Comment by ocornut** [comment]
Please provide a calllstack and make sure that the memory region and size passed to the memory editor are valid.

**Comment by osa3301** [comment]
This is how I render imgui
![image](https://user-images.githubusercontent.com/65470065/102541616-e9734700-40b0-11eb-82c2-ac05bca95cff.png)

Crash:
![image](https://user-images.githubusercontent.com/65470065/102541789-250e1100-40b1-11eb-9a36-ea3c8ca141f0.png)
![image](https://user-images.githubusercontent.com/65470065/102541805-2ccdb580-40b1-11eb-8859-6a0d806cfa63.png)
![image](https://user-images.githubusercontent.com/65470065/102541851-3ce59500-40b1-11eb-9d6d-94e668a3e620.png)

**Comment by ocornut** [comment]
Sorry but https://github.com/ocornut/imgui/issues/1586

**Comment by winta0227** [comment]
lol
