### ISSUE TITLE
Memory Editor: Scrollbar isn't getting drawn

### ISSUE THREAD

**Issue by ghost** [ocornut/imgui_club#28]
I'm using the vanilla library, I did not modify it whatsoever, yet, the scrollbar isn't getting drawn from what I can see. I hope I didn't just miss some detail thus wasting your time, and I hope we can eventually find the root of the problem, because it works in all the other projects that use this memory editor. I'm attaching a screenshot that shows the metrics and the memory editor widget:
![NoScrollbarIsPresent](https://user-images.githubusercontent.com/91993281/142292169-ccf7a568-2f43-4196-89e6-c60fb366ca70.png)
Update: it is this problem #20 :smile: My address range occupies the entire 32-bit address space... (it is for a Nintendo 64 emulator). I guess I'm just going to try to modify the library and propose a solution. Sorry for wasting your time

**Comment by CocoSimone** [comment]
I'm reopening this because now it just stopped drawing no matter how big the address range is and I have no idea why. Again, it's all vanilla. Screenshot attached below.
![image](https://user-images.githubusercontent.com/91993281/142482758-cf2deb32-3e88-42aa-87cb-aeb8794c5005.png)

**Comment by CocoSimone** [comment]
I'm reopening this because now it just stopped drawing no matter how big the address range is and I have no idea why. Again, it's all vanilla. Screenshot attached below.
![image](https://user-images.githubusercontent.com/91993281/142482758-cf2deb32-3e88-42aa-87cb-aeb8794c5005.png)
