### ISSUE TITLE
Can't compile imgui_freetype with recent imgui

### ISSUE THREAD

**Issue by StuartSulaski** [ocornut/imgui_club#3]
Hi,

I'm trying to compile imgui_freetype with dear_imgui version 1.51 but I'm getting a few errors.
One of which indicates that ImFontAtlasBuildRegisterDefaultCustomRects(atlas) could not be found which lets me believe this function existed in a previous version of dear_imgui but I might be wrong as I don't see any mention of it in API changelog.
The other errors are the same but for other variables or function calls.
I was just wondering if I was missing something obvious.
If my issue isn't clear enough please let me know.

Thanks in advance for your help

**Comment by ocornut** [comment]
You are not using the latest master version of imgui. This function was added at the same time I added the imgui_freetype code

**Comment by StuartSulaski** [comment]
Yep I just realised it myself, silly mistake

Thanks
