### ISSUE TITLE
suggestion: separate each plugin into their respective repositories

### ISSUE THREAD

**Issue by 413x1nkp** [ocornut/imgui_club#45]
I think it'll be better for organizing if all of the plugins had each their own repositories, then this repository can include them as git submodules, this way all of the plugins can be downloaded in a batch using this repo or each plugin can be downloaded separately from their own repos using `git clone`

**Comment by HACKE-RC** [comment]
Yep and to also include them as submodules will be easier if I only want to have one of them

**Comment by RicoP** [comment]
Meh. Having them in one repo is more convenient

**Comment by 413x1nkp** [comment]
> Meh. Having them in one repo is more convenient

that's not the point, I'm talking about making a repo for each plugin and then simply adding them as a submodule in this one.

**Comment by RicoP** [comment]
> > Meh. Having them in one repo is more convenient
> 
> that's not the point, I'm talking about making a repo for each plugin and then simply adding them as a submodule in this one.

But that is just making things more bothersome. Then I have to checkout submodules recursively after cloning and many people forget about that. It would also break existing repos that already have this repo checked in as submodule which would break all active repoitories right now, for what benefit? 

What's the gain ?

**Comment by 413x1nkp** [comment]
> > > Meh. Having them in one repo is more convenient
> > 
> > 
> > that's not the point, I'm talking about making a repo for each plugin and then simply adding them as a submodule in this one.
> 
> But that is just making things more bothersome. Then I have to checkout submodules recursively after cloning and many people forget about that. It would also break existing repos that already have this repo checked in as submodule which would break all active repoitories right now, for what benefit?
> 
> What's the gain ?

The gain in separating all of the plugins is easily visible when you only want ONE plugin instead of a bunch.

So, This:
1. allows to save on bandwidth
2. makes it more convenient to get only the plugins that you want

If you wanted all of the plugins, You'd just do `git clone --recursive`, which is no trouble at all for anyone, but if You force users to clone EVERY SINGLE PLUGIN even if they only want one, that becomes a problem if a user doesn't have a strong internet connection

This wouldn't break existing repositories that depend on this one either, as `git clone --recursive` will RECURSIVELY clone ALL of the dependencies, even the dependencies of the dependencies. If You specify `depth` as a param for git clone, then You'd just increment the depth by 1 which is again, no trouble at all for anyone.

**Comment by RicoP** [comment]
Bandwidth? This repo has two header files and one cpp file...

**Comment by ocornut** [comment]
> clone EVERY SINGLE PLUGIN even if they only want one, that becomes a problem if a user doesn't have a strong internet connection

Loading **THIS GITHUB WEBPAGE YOU ARE READING NOW WITH 6 MESSAGES** downloads more contents than the imgui_club/ git repository.

Git Submodules are their own source of problem.

If you only want a single point you may as well directly download it.

This sounds more complicated and not worth it, sorry.

**Comment by 413x1nkp** [comment]
> > clone EVERY SINGLE PLUGIN even if they only want one, that becomes a problem if a user doesn't have a strong internet connection
> 
> Loading **THIS GITHUB WEBPAGE YOU ARE READING NOW WITH 6 MESSAGES** downloads more contents than the imgui_club/ git repository.
> 
> Git Submodules are their own source of problem.
> 
> If you only want a single point you may as well directly download it.
> 
> This sounds more complicated and not worth it, sorry.

Why'd this become an issue of bandwidth all of a sudden? It was just one benefit I've listed, there are also others.
Overall, it's okay if that's not planned, `curl` is still an option I guess, but seamless git integration would just be nicer to have, I think

**Comment by ocornut** [comment]
I understand but I have to aggressively reduce general maintenance complexity and it includes not having too many repository. My sanity is the main bottleneck of imgui progress.
